# A voir pour K8S .....
# Staging
- name: staging
  ip: 192.168.60.21
  cpus: 1
  mem: 2048
  os: ubuntu/focal64
  docker: required
  provisioner: ansible
  playbook: provisionning/staging.yml
# Production (Apache, java project)
- name: production
  ip: 192.168.60.22
  cpus: 1
  mem: 2048
  os: ubuntu/focal64
  docker: required
  provisioner: ansible
  playbook: provisionning/production.yml
# CI-Server (Jenkins/sonarqube/jfrog)
- name: server
  ip: 192.168.60.10
  cpus: 2
  mem: 8192
  os: ubuntu/focal64
  docker: required
  provisioner: ansible
  playbook: provisionning/server.yml
# Monitoring (Prometheus/Grafana & ELK)
#- name: monitoring
#  ip: 192.168.60.11
#  cpus: 1
#  mem: 2048
#  os: ubuntu/focal64
#  docker: required
#  provisioner: none
#  playbook: provisioning/monitoring.yml
# Dev machine voir pour une boucle
- name: dev1
  ip: 192.168.60.101
  cpus: 1
  mem: 1024
  os: ubuntu/focal64
  docker: required
  provisioner: ansible
  playbook: provisionning/dev-machine.yml