  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes

  - name: Install nano
    apt:
      name: nano
      state: present

  - name: Install unzip
    apt:
      name: unzip
      state: present