- name: Install and configure a staging machine
  become: yes
  hosts: monitoring
  tasks:
  - name: import
    ansible.builtin.import_tasks: 
      file: base.yml
                                      
  - name: java
    ansible.builtin.import_tasks: 
      file: java.yml

  - name: install de prometheus
    ansible.builtin.import_tasks: 
      file: monitoring/prometheus.yml